[theme]
base="dark"
baseRadius = "1rem"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter&display=swap"
codeFont = "'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"
